name: Prettier Check

on:
  push:
    branches: [main, master]
  pull_request:
    types: [synchronize, opened, reopened, ready_for_review, unlabeled]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Prettier Check
        run: |
          npm install prettier prettier-plugin-motoko --no-save
          npx -y prettier --plugin prettier-plugin-motoko --check '**/*.{mo,json,md}'
